
List<Map<String, dynamic>> bolimlar = [
  {"name": "Xayrlashuv", "img": "assets/png/1.png"},
  {"name": "Murojat", "img": "assets/png/2.png"},
  {"name": "Tanishuv", "img": "assets/png/3.png"},
  {"name": "Uchrashuv", "img": "assets/png/4.png"},
  {"name": "Xushmuomilalik", "img": "assets/png/5.png"},
  {"name": "Rozilik", "img": "assets/png/6.png"},
  {"name": "Inkor", "img": "assets/png/7.png"},
  {"name": "Tilaklar", "img": "assets/png/8.png"},
  {"name": "Iltimos", "img": "assets/png/9.png"},
  {"name": "Afsuslanish", "img": "assets/png/10.png"},
  {"name": "Taklif", "img": "assets/png/11.png"},
  {"name": "Dorixonada", "img": "assets/png/12.png"},
  {"name": "Kasallik", "img": "assets/png/13.png"},
  {"name": "Militsiya", "img": "assets/png/14.png"},
  {"name": "Go'zallik Saloni", "img": "assets/png/15.png"},
  {"name": "Sartaroshxona", "img": "assets/png/16.png"},
  {"name": "Shifokor", "img": "assets/png/17.png"},
  {"name": "Soat Ustasi", "img": "assets/png/18.png"},
  {"name": "Sport", "img": "assets/png/19.png"},
  {"name": "Uy Ro'zg'or", "img": "assets/png/20.png"},
  {"name": "Zaruriy ma'lumotlar", "img": "assets/png/21.png"},
  {"name": "Attorlik", "img": "assets/png/22.png"},
  {"name": "Bank", "img": "assets/png/23.png"},
  {"name": "Avtobusda", "img": "assets/png/24.png"},
  {"name": "Bojhona", "img": "assets/png/25.png"},
  {"name": "Diqqatga sazovor joylar", "img": "assets/png/26.png"},
  {"name": "Dokonda kerakli so'zlar", "img": "assets/png/27.png"},
  {"name": "Gullar", "img": "assets/png/29.png"},
  {"name": "Hayvonot bog'ida", "img": "assets/png/30.png"},
  {"name": "Muzey", "img": "assets/png/31.png"},
  {"name": "Iltimos", "img": "assets/png/32.png"},
  {"name": "Inkor", "img": "assets/png/33.png"},
  {"name": "Kasb", "img": "assets/png/34.png"},
  {"name": "Kema", "img": "assets/png/35.png"},
  {"name": "Kerakli so'zlar 1", "img": "assets/png/26.png"},
  {"name": "Kerakli so'zlar 2", "img": "assets/png/27.png"},
  {"name": "Kerakli so'zlar 3", "img": "assets/png/29.png"},
  {"name": "Kerakli so'zlar 4", "img": "assets/png/30.png"},
  {"name": "Kerakli so'zlar 5", "img": "assets/png/31.png"},
  {"name": "Kerakli so'zlar 6", "img": "assets/png/32.png"},
  {"name": "Kerakli so'zlar 7", "img": "assets/png/33.png"},
  {"name": "Kerakli so'zlar 8", "img": "assets/png/34.png"},
  {"name": "Kerakli so'zlar 9", "img": "assets/png/35.png"},

  {"name": "Kino va Kansert", "img": "assets/png/31.png"},
  {"name": "Kiyimlar", "img": "assets/png/32.png"},
  {"name": "Konstovarlar", "img": "assets/png/33.png"},
  {"name": "Kasb", "img": "assets/png/34.png"},
  {"name": "Kema", "img": "assets/png/35.png"},
];


