List kasallik = [
  {"uz": "uyqusizlik", "esp": "insomnio"},
  {"uz": "...og'riq", "esp": "dolor..."},
  {"uz": "-yonboshdagi", "esp": "-en el costado"},
  {"uz": "-ko'krakdagi", "esp": "-en el pecho"},
  {"uz": "-qorindagi", "esp": "-en el estómago"},
  {"uz": "-orqadagi", "esp": "-en la espalda"},
  {"uz": "-yurakdagi", "esp": "-en el corazón"},
  {"uz": "-boshdagi", "esp": "-de cabeza"},
  {"uz": "-zirqiratadigan", "esp": "-molesto"},
  {"uz": "-o'tkir", "esp": "-agudo"},
  {"uz": "-bo'g'iq ", "esp": "-sordo"},
  {"uz": "bosh aylanishi ", "esp": "vértigo"},
  {"uz": "og'izni bemazaligi", "esp": "amargura en la boca"},
  {"uz": "isitma", "esp": "fiebre"},
  {"uz": "oshqazon qaynashi", "esp": "quemazón"},
  {"uz": "qorin dam bo'lishi ", "esp": "estreñimiento"},
  {"uz": "oshqazonda achishish", "esp": "ardor, pirosis"},
  {"uz": "yo'tal", "esp": "tos"},
  {"uz": "qon ketishi ", "esp": "hemorragia"},
  {"uz": "qon tuflash ", "esp": "esputo hemorrágico"},
  {"uz": "...qon bosimi", "esp": "presión arterial..."},
  {"uz": "-yuqori", "esp": "-alta"},
  {"uz": "-past", "esp": "-baja"},
  {"uz": "shamollash", "esp": "catarro"},
  {"uz": "hushdan ketish", "esp": "desmayo"},
  {"uz": "umumiy holsizlik ", "esp": "malestar general"},
  {"uz": "nafas qisishi", "esp": "ahogo"},
  {"uz": "ishtahani yo'qolishi", "esp": "falta de apetito"},
  {"uz": "yomon ishtaha", "esp": "mal apetito"},
  {"uz": "yuqori harorat", "esp": "temperatura elevada"},
  {"uz": "ich ketishi", "esp": "diarrea"},
  {"uz": "holsizlik", "esp": "debelidad"},
  {"uz": "uyqusirash", "esp": "somnolencia"},
  {"uz": "ko'ngil aynishi", "esp": "náuseas"},
];

List tanaAzo = [
  {"uz": "ko'z", "esp": "ojo"},
  {"uz": "bosh", "esp": "cabeza"},
  {"uz": "tomoq", "esp": "garganta"},
  {"uz": "ko'krak", "esp": "pecho"},
  {"uz": "qorin", "esp": "vientre"},
  {"uz": "oyoq", "esp": "pierna"},
  {"uz": "burun", "esp": "nariz"},
  {"uz": "oyoq barmog'i", "esp": "dedo del pie"},
  {"uz": "qo'l barmog'i", "esp": "dedo de la mano"},
  {"uz": "qo'l", "esp": "brazo"},
  {"uz": "elka", "esp": "espalda"},
  {"uz": "quloq", "esp": "oreja"},
  {"uz": "bo'yin", "esp": "cuello"},
  {"uz": "til", "esp": "lengua"},
  {"uz": "ichki azolar", "esp": "visceras"},
  {"uz": "o'n ikki barmoqli ichak", "esp": "duodeno"},
  {"uz": "oshqozon", "esp": "estómago"},
  {"uz": "o't qopi", "esp": "vesícula biliar"},
  {"uz": "ichak", "esp": "intestino"},
  {"uz": "o'pkalar", "esp": "pulmones"},
  {"uz": "bachadon", "esp": "matríz"},
  {"uz": "siydiq qopi", "esp": "vejiga urinaria"},
  {"uz": "jigar", "esp": "hígado"},
  {"uz": "oshqazon osti bezi", "esp": "pancrea"},
  {"uz": "buyraklar", "esp": "riñones"},
  {"uz": "prostata", "esp": "próstata"},
  {"uz": "taloq", "esp": "bazo"},
  {"uz": "yurak", "esp": "corazón"},
  {"uz": "qalqonsimon bez", "esp": "glándula tiroidea"},
  {"uz": "kasalliklar", "esp": "enfermedades"},
  {"uz": "allergiya", "esp": "alergia"},
  {"uz": "angina", "esp": "angina"},
  {"uz": "appenditsit (ko'r ichak)", "esp": "apendicitis"},
  {"uz": "bronxit (bronxlar shamollashi)", "esp": "bronquitis"},
  {"uz": "shamollash", "esp": "inflamación"},
  {"uz": "o'pkalar shamollashi", "esp": "pulmonía"},
  {"uz": "qo'l oyoq chiqishi", "esp": "luxación"},
  {"uz": "gastrit (oshqazon yallig'lanishi kasalligi)", "esp": "gastritis"},
  {"uz": "gripp (tumov)", "esp": "gripe"},
  {"uz": "diarreya (ich ketishi)", "esp": "diarrea"},
  {"uz": "dizenteriya", "esp": "disentería"},
  {"uz": "difteriya", "esp": "diftería"},
  {"uz": "insult (miya qon tomiri yorilishi)", "esp": "Insulto, derrame"},
  {"uz": "dengiz kasalligi", "esp": "Mareo "},
  {"uz": "absess (yarani yiringlashi)", "esp": "absceso"},
  {"uz": "kuyish", "esp": "quemadura"},
  {"uz": "saraton", "esp": "tumor"},
  {"uz": "sinish", "esp": "fractura"},
  {"uz": "ovqatdan zaharlanish", "esp": "intoxicación de alimentos"},
  {"uz": "shamollash", "esp": "resfríado"},
  {"uz": "oshqazonni buzilishi", "esp": "indegestión"},
  {"uz": "yurak xuruji", "esp": "ataque del corazón"},
  {"uz": "xoletsistit (o't qopi shamollashi)", "esp": "colecistitis"},
  {"uz": "Oshkozon yarasi", "esp": "ulcera"},
  {"uz": "tish shifokori ko'rigi ", "esp": "consultando a un dentista "},
  {
    "uz": "Menga yaxshi tish shifokorini tavsiya bera olasizmi? ",
    "esp": "¿Puede usted recomendarme un buen dentista? "
  },
  {"uz": "Meni jag' tishim og'riyapti", "esp": "Me duele una muela/un diente"},
  {"uz": "Meni milkim shamollagan", "esp": "Se me ha inflamado la encía"},
  {"uz": "Meni plombam tushib ketdi", "esp": "Se me ha caído el empaste"},
  {"uz": "Meni...og'riyapti", "esp": "Me duele..."},
  {"uz": "-o'ng tomondagi jag' tishim", "esp": "-una muele a la derecha"},
  {"uz": "-chap tomondagi jag' tishim", "esp": "-una muele a la izquierda"},
  {"uz": "-past tomondagi jag' tishim", "esp": "-una muele de abajo"},
  {"uz": "-yuqori tomondagi jag' tishim", "esp": "-una muele de arriba"},
  {"uz": "-tishim", "esp": "-un diente"},
  {"uz": "-mana bu qoziq tishim", "esp": "-esta muela"},
  {
    "uz": "Iltimos, og'riq qoldiruvchi qiling",
    "esp": "Hágame anestesia, por favor"
  },
  {"uz": "Menga.... qilishlarini xoxlayman", "esp": "Quiero que me pongan..."},
  {"uz": "-koronka", "esp": "-la corona"},
  {"uz": "-protez", "esp": "-la prótesia"},
  {
    "uz": "Protezni to'g'irlay olasizlarmi?",
    "esp": "¿Pueden arreglarme la prótesia?"
  },
  {"uz": "Qachon tayyor bo'ladi?", "esp": "¿Cuándo estará listo?"},
  {"uz": "Keyingi safar qachon kelay?", "esp": "¿Cuándo vengo la próxima vez?"},
];
